import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * AI 유지보수 가이드 (JSDoc)
 * @description
 * 이 파일은 도움말 문서(Docs)의 사이드바 메뉴를 구성합니다.
 * 현재 `autogenerated` 속성을 사용하여 `docs/` 폴더 내의 마크다운 파일들의 
 * `sidebar_position`과 `sidebar_label` 프론트매터(Frontmatter)를 읽어와 
 * 자동으로 메뉴 계층을 생성하도록 설정되어 있습니다.
 * (CMS에서 문서를 작성하면 이 사이드바에 자동으로 나타납니다.)
 */
const sidebars: SidebarsConfig = {
  // 자동으로 사이드바를 생성합니다. CMS 연동에 최적화된 방식입니다.
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;

